### ISSUE TITLE
Walker: ขอ orderItem แบบ ละเอียด

### ISSUE THREAD

**Issue by TempestZef** [Ditto-KU/Backend#70]
หลักๆ
- orderItem สามารถเก็บ ชื่อร้านได้หลายร้าน
- ในแต่ละร้าน สามารถมีเมนูได้มากกว่าหนึ่ง
- รายละเอียดของแต่ละเมนูต้องมี จำนวนที่สั่ง/ข้อมูลเพิ่มเติม/ชื่อเมนู
- (เป็นไปได้ เพิ่มราคารวมแต่ละเมนูด้วย)

**Comment by LaZGram** [comment]
Finish wait Pull Req
