### ISSUE TITLE
add this two path in /admin

### ISSUE THREAD

**Issue by Puplaroid** [Ditto-KU/Backend#96]
1. https://ku-man-api.vimforlanie.com/api#/SHOP/ShopController_updateShopStatus
    Update shop status to open or close
2.https://ku-man-api.vimforlanie.com/api#/SHOP/ShopController_updateMenuStatus
    Update menu status to open or close

**Comment by Rmjp** [comment]
@LaZGram

**Comment by LaZGram** [comment]
ทำแล้ว

**Comment by Puplaroid** [comment]
อยู่ไหนอะ

**Comment by LaZGram** [comment]
เดี๋ยวก็เห็น
